# Ersetze die Platzhalter mit deinen echten Usernamen/Links

#github: [dein_github_username] # Wenn du bei GitHub Sponsors angemeldet bist
#patreon: dein_username
#ko_fi: dein_username
custom: ["https://buymeacoffee.com/qpmonkey"]